# Default values for capture proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: migrations/capture_proxy
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 9201 # Port exposed to external
  targetPort: 9200 # Container port

container:
  command: "/runJavaWithClasspath.sh org.opensearch.migrations.trafficcapture.proxyserver.CaptureProxy --kafkaConnection kafka-cluster-kafka-bootstrap:9092 --destinationUri  https://elasticsearch:19200  --insecureDestination --listenPort 9200 --sslConfigFile /usr/share/elasticsearch/config/proxy_tls.yml --otelCollectorEndpoint http://localhost:4317"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

otelCollectorSidecar:
  name: otel-collector
  enabled: true
  restartPolicy: "Always"
  #args: "--config=/etc/otel-config-debug-only.yaml"
  #args: ["--config=/etc/otel-config-prometheus-jaeger.yaml"]
  image:
    repository: migrations/otel_collector
    pullPolicy: IfNotPresent
    tag: "latest"
  ports:
    - name: pprof
      containerPort: 1888
      protocol: TCP
    - name: health-check
      containerPort: 13133
      protocol: TCP
    - name: zpages
      containerPort: 55679
      protocol: TCP
    - name: otlp-receiver
      containerPort: 4317
      protocol: TCP
#    - name: prom-metrics
#      containerPort: 8888
#      protocol: TCP
#    - name: prom-exporter
#      containerPort: 8889
#      protocol: TCP
