receivers:
  otlp:
    protocols:
      grpc:
processors:
  cumulativetodelta:
  probabilistic_sampler/traces:
    sampling_percentage: ${env:TRACE_SAMPLING_PERCENTAGE:-1}
  resource/stage:
    attributes:
      - key: stage
        value: ${env:STAGE:-unknown}
        action: upsert
      - key: telemetry.sdk.language
        action: delete
      - key: telemetry.sdk.name
        action: delete
      - key: telemetry.sdk.version
        action: delete
  batch:
    timeout: 10s
    send_batch_size: 8192
    send_batch_max_size: 10000
extensions:
  health_check:
exporters:
  awsemf:
    namespace: 'OpenSearchMigrations'
    resource_to_telemetry_conversion:
      enabled: true
    detailed_metrics: true
    retain_initial_value_of_delta_metric: true
    dimension_rollup_option: NoDimensionRollup
  awsxray:
    index_all_attributes: true
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [cumulativetodelta, resource/stage, batch]
      exporters: [awsemf]
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler/traces, batch]
      exporters: [awsxray]
