receivers:
  otlp:
    protocols:
      grpc:
processors:
  cumulativetodelta:
  probabilistic_sampler/traces:
    sampling_percentage: ${env:TRACE_SAMPLING_PERCENTAGE:-1}
  resource/metrics:
    attributes:
      - key: qualifier
        value: ${env:QUALIFIER}
        action: upsert
  batch:
    timeout: 10s
    send_batch_size: 8192
    send_batch_max_size: 10000
extensions:
  health_check:
exporters:
  awsemf:
    namespace: 'OpenSearchMigrations'
    dimension_rollup_option: NoDimensionRollup # Reduce number of metrics by only publishing most granular metric
    metric_declarations:
      - dimensions: [ [ "qualifier" ] ]
        metric_name_selectors: [ ".*" ]
  awsxray:
    index_all_attributes: true
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [cumulativetodelta, resource/metrics, batch]
      exporters: [awsemf]
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler/traces, batch]
      exporters: [awsxray]
