apiVersion: apps/v1
kind: Deployment
metadata:
  name: replayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: replayer
  template:
    metadata:
      labels:
        app: replayer
    spec:
      containers:
      - name: replayer
        image: 'migrations/traffic_replayer:latest'
        command: ["/bin/sh", "-c", "/runJavaWithClasspath.sh org.opensearch.migrations.replay.TrafficReplayer --speedup-factor 2 https://opensearchtarget:9200 --auth-header-value Basic\\ YWRtaW46bXlTdHJvbmdQYXNzd29yZDEyMyE= --insecure --kafka-traffic-brokers kafka:9092 --kafka-traffic-topic logging-traffic-topic --kafka-traffic-group-id logging-group-default --otelCollectorEndpoint http://otel-collector:4317"]
        volumeMounts:
        - name: shared-replayer-output
          mountPath: /shared-replayer-output
      volumes:
      - name: shared-replayer-output
        persistentVolumeClaim:
          claimName: replayer-pvc
