---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-executor
  namespace: ma
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-deployer-role
  namespace: ma
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-deployer-rolebinding
  namespace: ma
subjects:
  - kind: ServiceAccount
    name: argo-workflow-executor
    namespace: ma
roleRef:
  kind: Role
  name: workflow-deployer-role
  apiGroup: rbac.authorization.k8s.io