
migration-console:
  enabled: true
  replicaCount: 1
  image:
    repository: migrations/migration_console
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    SHARED_LOGS_DIR_PATH: /shared-logs-output/traffic-replayer-default
  volumes:
    # For minikube required: minikube mount <local_path>/opensearch-migrations:/opensearch-migrations
    - name: services-yaml
      hostPath:
        path: /opensearch-migrations/TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/services.yaml
        type: File
    - name: shared-logs
      persistentVolumeClaim:
        claimName: shared-logs-pvc
    - name: snapshot-vol
      persistentVolumeClaim:
        claimName: snapshot-vol-pvc
  volumeMounts:
    - name: services-yaml
      mountPath: /etc/migration_services.yaml
    - name: shared-logs
      mountPath: /shared-logs-output
    - name: snapshot-vol
      mountPath: /storage

capture-proxy:
  enabled: true
  replicaCount: 1
  image:
    repository: migrations/capture_proxy
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: LoadBalancer
    port: 9201 # Port exposed to external
    targetPort: 9200 # Container port
  container:
    command: >
      /runJavaWithClasspath.sh org.opensearch.migrations.trafficcapture.proxyserver.CaptureProxy
      --kafkaConnection kafka-cluster-kafka-bootstrap:9092
      --destinationUri  https://elasticsearch:19200
      --insecureDestination
      --listenPort 9200
      --sslConfigFile /usr/share/elasticsearch/config/proxy_tls.yml
      --otelCollectorEndpoint http://localhost:4317
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

