apiVersion: batch/v1
kind: Job
metadata:
  name: console-config-validation-{{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"  # Same weight as flag creation
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccountName: config-validator
      containers:
        - name: validator
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              # Check for existing flag
              FLAG=$(kubectl get configmap shared-config-mode -o jsonpath='{.data.enabled}' 2>/dev/null || echo "")

              if [ -n "$FLAG" ]; then
                # Flag exists - must be true to install console
                if [ "$FLAG" == "false" ]; then
                  echo "Error: Cannot install console when the solution is already configured direct service configurations."
                  echo "Install the shared-config chart first, then update the individual services' useSharedConfig values as well as changing appropriate parameters to load from configMapName."
                  exit 1
                fi
              else
                # No flag - create it as true
                kubectl create configmap shared-config-mode --from-literal=enabled=true
              fi

              echo "Config mode validation passed"
      restartPolicy: Never