{{- if .Values.sharedLogVolume.createPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedLogVolume.pvcClaimName }}
spec:
  accessModes:
    - {{ .Values.sharedLogVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.sharedLogVolume.size }}
  {{- if .Values.sharedLogVolume.storageClass }}
  storageClassName: {{ .Values.sharedLogVolume.storageClass }}
  {{- end }}
{{- end }}

---
{{- if .Values.snapshotVolume.createPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.snapshotVolume.pvcClaimName }}
spec:
  accessModes:
    - {{ .Values.snapshotVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.snapshotVolume.size }}
  {{- if .Values.snapshotVolume.storageClass }}
  storageClassName: {{ .Values.snapshotVolume.storageClass }}
  {{- end }}
{{- end }}
