# Default values for elasticsearch
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: migrations/elasticsearch_searchguard
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 19200 # Port exposed to external
  targetPort: 9200 # Container port

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
