apiVersion: v2
name: grafana
description: A Helm chart for deploying Grafana
appVersion: "3.5.0"
version: 0.1.0
dependencies:
  - name: grafana
    version: "8.5.0"
    repository: "https://grafana.github.io/helm-charts"
