grafana:
  service:
    type: LoadBalancer
    port: 3000
    targetPort: 3000
  grafana.ini:
    auth:
      # Disable login form so anonymous users won't be prompted to log in
      disable_login_form: true
    auth.anonymous:
      # Enable anonymous access
      enabled: true
      # Set the role for anonymous users (e.g., Viewer, Editor)
      org_role: Editor
  ## Grafana data sources configuration
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server
          isDefault: true
          editable: true
        - name: Jaeger
          type: jaeger
          access: proxy
          url: http://jaeger-query:16686
          isDefault: false
          editable: true

  ## Set up the sidecar to import data sources (usually enabled by default)
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true
      label: grafana_dashboard

