# Default values for traffic replayer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: migrations/migration_console
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  SHARED_LOGS_DIR_PATH: /shared-logs-output/traffic-replayer-default

# For minikube required: minikube mount /Volumes/workplace/opensearch/lewijacn-migrations/opensearch-migrations:/opensearch-migrations
servicesYamlVolume:
  path: /opensearch-migrations/TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/services.yaml  # Local file path on the host
  mountPath: /etc/migration_services.yaml  # Path inside the container

sharedLogVolume:
  volumeName: shared-logs
  mountPath: /shared-logs-output # Path inside the container where the volume should be mounted
  pvcClaimName: shared-logs-pvc

snapshotVolume:
  volumeName: snapshot-vol
  mountPath: /storage # Path inside the container where the volume should be mounted
  pvcClaimName: snapshot-vol-pvc

test: true
