receivers:
  otlp:
    protocols:
        grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: capturereplay
    const_labels:
      label1: value1
  logging:
    loglevel: debug

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

  otlp/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
    endpoint: jaeger:4317
    tls:
      insecure: true


processors:
  # Processor to set the namespace based on the service name
  attributes/nscapture:
    actions:
      - key: namespace
        value: "capture"
        action: insert
      - key: service.name
        value: "capture"
        action: update
  attributes/nsreplayer:
    actions:
      - key: namespace
        value: "replay"
        action: insert
      - key: service.name
        value: "replay"
        action: update

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, zipkin, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [attributes/nscapture, attributes/nsreplayer]
      exporters: [logging, prometheus]
