version: '3.7'
services:
  webserver:
    image: 'testenv/nginx:latest'
    ports:
      - "8080:80"

  captureproxy:
    image: 'testenv/capture_proxy:latest'
    networks:
      - testing
    ports:
      - "9201:9201"
    command: /runJavaWithClasspath.sh org.opensearch.migrations.trafficcapture.proxyserver.Main --destinationUri  http://webserver:80 --listenPort 9201 --noCapture
    depends_on:
      - webserver

  jmeter:
    image: 'testenv/jmeter:latest'
    networks:
      - testing
    command: /bin/sh -c "while sleep 10; do /runJavaWithClasspath.sh org.opensearch.migrations.trafficcapture.JMeterLoadTest -p 9201 -d captureproxy; done"
    depends_on:
      - captureproxy



networks:
  testing:
    driver: bridge