apiVersion: v2
name: kafka-op
description: A Helm chart for deploying Strimzi Kafka Operator and Kafka Cluster
version: 0.1.0
appVersion: "3.5.0"
dependencies:
  - name: strimzi-kafka-operator
    version: 0.43.0
    repository: https://strimzi.io/charts/
