apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Load all env variables
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.sharedLogVolume.volumeName }}
              mountPath: {{ .Values.sharedLogVolume.mountPath }}
            - name: services-yaml-file
              mountPath: {{ .Values.servicesYamlVolume.mountPath }}
            - name: {{ .Values.snapshotVolume.volumeName }}
              mountPath: {{ .Values.snapshotVolume.mountPath }}
        {{- include "migrations-lib.otel-sidecar" . | indent 8 }}
      volumes:
        - name: {{ .Values.sharedLogVolume.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.sharedLogVolume.pvcClaimName }}
        - name: services-yaml-file
          hostPath:
            path: {{ .Values.servicesYamlVolume.path }}
            type: File
        - name: {{ .Values.snapshotVolume.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.snapshotVolume.pvcClaimName }}
