# Main Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "generic.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "generic.fullname" . }}
        env: v1
    spec:
      containers:
        - name: captureproxy
          image: migrations/capture_proxy:latest
          imagePullPolicy: IfNotPresent
          env:
          {{ include "generic.pullEnvVarsFromConfigMaps" (dict "PackageName" (include "generic.fullname" .) "Values" .Values "include" .Template.Include "Template" .Template) | indent 10 }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              {{- include "generic.buildCommandBuilderScript" (dict "Command" "/runJavaWithClasspath.sh org.opensearch.migrations.trafficcapture.proxyserver.CaptureProxy" "PackageName" (include "generic.fullname" .) "Values" .Values "include" .Template.Include "Template" .Template) | nindent 14 }}
          ports:
            - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
spec:
  selector:
    app: {{ include "generic.fullname" . }}
    env: v1
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
