# Default values for captured-traffic-kafka-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: dev  # Can be 'test' or 'prod'

kafka:
  dev:
    name: kafka-dev
    replicas: 1
    storageType: ephemeral
  prod:
    name: kafka-prod
    replicas: 3
    storageType: jbod
    storageSize: 100Gi