elasticsearch-local:
  fullnameOverride: "source-cluster"
  image: docker.elastic.co/elasticsearch/elasticsearch-oss
  imageTag: "7.10.2"

  replicas: 1

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  service:
    type: LoadBalancer
    ports:
      - name: http
        port: 9200
        protocol: TCP
        targetPort: 9200

  esConfig:
    elasticsearch.yml: |
      xpack:
        security:
          enabled: false
          transport:
            ssl:
              key: ""
      cluster.name: "docker-cluster"
      network.host: "0.0.0.0"
      discovery.type: "single-node"

  roles:
    - master
    - data
    - ingest
    - remote_cluster_client
