# Default values for reindex-from-snapshot.
parallelCount: 0
image:
  repository: migrations/reindex_from_snapshot
  pullPolicy: IfNotPresent
  tag: "latest"
container:
  command: >
    /rfs-app/runJavaWithClasspath.sh org.opensearch.migrations.RfsMigrateDocuments
    --snapshot-local-dir /storage/snapshot
    --snapshot-name rfs-snapshot
    --lucene-dir /storage/lucene
    --target-host https://opensearch-cluster-master:9200
    --target-username admin
    --target-password myStrongPassword123!
    --target-insecure
    --max-shard-size-bytes 85899345920
    --otel-collector-endpoint http://localhost:4317
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  - name: SHARED_LOGS_DIR_PATH
    value: /shared-logs-output/reindex-from-snapshot-default
volumes:
  - name: shared-logs
    persistentVolumeClaim:
      claimName: shared-logs-pvc
  - name: snapshot-vol
    persistentVolumeClaim:
      claimName: snapshot-vol-pvc
volumeMounts:
  - name: shared-logs
    mountPath: /shared-logs-output
  - name: snapshot-vol
    mountPath: /storage
