# Default values for reindex-from-snapshot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

parallelCount: 0

image:
  repository: migrations/reindex_from_snapshot
  pullPolicy: IfNotPresent
  tag: "latest"

container:
  command: >
    /rfs-app/runJavaWithClasspath.sh org.opensearch.migrations.RfsMigrateDocuments
    --snapshot-local-dir /storage/snapshot
    --snapshot-name rfs-snapshot
    --lucene-dir /storage/lucene
    --target-host https://opensearch-cluster-master:9200
    --target-username admin
    --target-password myStrongPassword123!
    --target-insecure
    --max-shard-size-bytes 85899345920
    --otel-collector-endpoint http://localhost:4317

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  SHARED_LOGS_DIR_PATH: /shared-logs-output/reindex-from-snapshot-default

otelCollectorSidecar:
  name: otel-collector
  enabled: true
  restartPolicy: "Always"
  #args: "--config=/etc/otel-config-debug-only.yaml"
  #args: ["--config=/etc/otel-config-prometheus-jaeger.yaml"]
  image:
    repository: migrations/otel_collector
    pullPolicy: IfNotPresent
    tag: "latest"
  ports:
    - name: pprof
      containerPort: 1888
      protocol: TCP
    - name: health-check
      containerPort: 13133
      protocol: TCP
    - name: zpages
      containerPort: 55679
      protocol: TCP
    - name: otlp-receiver
      containerPort: 4317
      protocol: TCP
#    - name: prom-metrics
#      containerPort: 8888
#      protocol: TCP
#    - name: prom-exporter
#      containerPort: 8889
#      protocol: TCP

sharedLogVolume:
  volumeName: shared-logs
  mountPath: /shared-logs-output # Path inside the container where the volume should be mounted
  pvcClaimName: shared-logs-pvc

snapshotVolume:
  volumeName: snapshot-vol
  mountPath: /storage # Path inside the container where the volume should be mounted
  pvcClaimName: snapshot-vol-pvc
