apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: capture-replay
spec:
  entrypoint: run-all
  serviceAccountName: argo-workflow-executor

  templates:
    - name: run-all
      inputs:
        parameters:
            # temporary - just to launch a migration console
          - name: source-config
            value: ""
            # Kafka setup
          - name: provided-kafka-bootstrap-servers
            value: ""
          - name: kafka-prefix
            value: "ct"
          - name: topic-name
            value: "logging-traffic-topic"
          - name: topic-partitions
            value: ""
            # Proxy setup
          - name: proxy-destination
          - name: proxy-listen-port
            # Replayer setup
          - name: replayer-target-config
      dag:
        tasks:
          - name: id-generator
            template: do-nothing

          - name: kafka-setup
            templateRef:
              name: kafka-setup
              template: cluster-topic-deploy
            when: "'{{inputs.parameters.provided-kafka-bootstrap-servers}}' == ''"
            dependencies: [ id-generator ]
            arguments:
              parameters:
                - name: kafka-name
                  value: "{{inputs.parameters.kafka-prefix}}-{{=last(split(tasks['id-generator'].id, '-'))}}"
                - name: topic-name
                  value: "{{inputs.parameters.topic-name}}"
                - name: topic-partitions
                  value: "{{inputs.parameters.topic-partitions}}"

          - name: get-brokers-list
            template: get-brokers-list
            dependencies: [ kafka-setup ]
            arguments:
              parameters:
                - name: created-bootstrap-servers
                  value: "{{tasks.kafka-setup.outputs.parameters.bootstrap-servers}}"
                - name: provided-kafka-bootstrap-servers
                  value: "{{inputs.parameters.provided-kafka-bootstrap-servers}}"

          - name: deploy-capture-proxy
            templateRef:
              name: capture-proxy
              template: deploy-capture-proxy
            dependencies: [ get-brokers-list ]
            arguments:
              parameters:
                - name: backside-uri-string
                  value: "{{=fromJSON(inputs.parameters['proxy-destination'])['endpoint']}}"
                - name: allow-insecure-connections-to-backside
                  value: "{{=fromJSON(inputs.parameters['proxy-destination'])['allow_insecure']}}"
                - name: frontside-port
                  value: "{{inputs.parameters.proxy-listen-port}}"
                - name: kafka-connection
                  value: "{{tasks.get-brokers-list.outputs.parameters.bootstrap-servers}}"
                - name: kafka-topic
                  value: "{{inputs.parameters.topic-name}}"

          - name: deploy-replayer
            templateRef:
              name: replayer
              template: deploy-replayer
            dependencies: [ get-brokers-list ]
            arguments:
              parameters:
                - name: target-url
                  value: "{{=fromJSON(inputs.parameters['replayer-target-config'])['endpoint']}}"
                - name: insecure
                  value: "{{=fromJSON(inputs.parameters['replayer-target-config'])['allow_insecure']}}"
                - name: auth-header-value
                  value: "{{=let a=fromJSON(inputs.parameters['replayer-target-config'])['basic_auth']; a==nil ? '' : 'Basic ' + toBase64(a['username'] + ':' + a['password'])}}"
                - name: speedup-factor
                  value: "20.0"
                - name: kafka-traffic-brokers
                  value: "{{tasks.get-brokers-list.outputs.parameters.bootstrap-servers}}"
                - name: kafka-traffic-topic
                  value: "logging-traffic-topic"
                - name: kafka-traffic-group-id
                  value: "{{tasks.id-generator.id}}"
                - name: replicas
                  value: 2

          - name: run-migration-console
            templateRef:
              name: migration-console-template
              template: deploy-console
            dependencies: [ get-brokers-list ]
            arguments:
              parameters:
                - name: source-cluster
                  value: "{{inputs.parameters.source-config}}"
                - name: target-cluster
                  value: "{{inputs.parameters.replayer-target-config}}"
                - name: command
                  value: tail -f /dev/null

          - name: get-user-satisfied-confirmation
            template: get-user-satisfied-confirmation
            dependencies: [ deploy-capture-proxy, deploy-replayer, run-migration-console ]

    - name: get-brokers-list
      steps: [[]]
      inputs:
          parameters:
            - name: created-bootstrap-servers
            - name: provided-kafka-bootstrap-servers
      outputs:
        parameters:
          - name: bootstrap-servers
            valueFrom:
              expression: "inputs.parameters['provided-kafka-bootstrap-servers'] == '' ? inputs.parameters['created-bootstrap-servers'] : inputs.parameters['provided-kafka-bootstrap-servers']"

    - name: get-user-satisfied-confirmation
      suspend: {}

    - name: do-nothing
      steps: [ [ ] ]