apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: migration-console-template
spec:
  entrypoint: run-migration-command
  templates:
    - name: get-console-config
      inputs:
        parameters:
          - name: source-cluster
            default: ""
            description: "Source cluster configuration (JSON)"
          - name: target-cluster
            default: ""
            description: "Target cluster configuration (JSON)"
          - name: snapshot-info
            default: ""
            description: "Snapshot configuration information (JSON)"
      outputs:
        parameters:
          - name: config-contents
            valueFrom:
              expression: >-
                (inputs.parameters['source-cluster'] != "" ? "source_cluster: " + inputs.parameters['source-cluster'] + "\n" : "") + 
                (inputs.parameters['target-cluster'] != "" ? "target_cluster: " + inputs.parameters['target-cluster'] + "\n" : "") + 
                (inputs.parameters['snapshot-info'] != "" ? "snapshot: " + inputs.parameters['snapshot-info'] + "\n" : "")
      steps: [[]]

    - name: run-console-with-config
      inputs:
        parameters:
          - name: command
          - name: config-contents
      container:
        image: migrations/migration_console:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e -x
            cat <<'EOF' > /config/migration_services.yaml
            {{inputs.parameters.config-contents}}
            EOF
            
            . /etc/profile.d/venv.sh
            source /.venv/bin/activate
            
            echo file dump
            echo ---
            cat /config/migration_services.yaml
            echo ---
            
            {{inputs.parameters.command}}

    - name: run-console
      inputs:
        parameters:
          - name: command
          - name: source-cluster
            default: ""
          - name: target-cluster
            default: ""
          - name: snapshot-info
            default: ""
      steps:
        - - name: get-console-config
            template: get-console-config
            arguments:
              parameters:
                - name: source-cluster
                  value: "{{inputs.parameters.source-cluster}}"
                - name: target-cluster
                  value: "{{inputs.parameters.target-cluster}}"
                - name: snapshot-info
                  value: "{{inputs.parameters.snapshot-info}}"
        - - name: run-console-with-config
            template: run-console-with-config
            arguments:
              parameters:
                - name: config-contents
                  value: "{{steps.get-console-config.outputs.parameters.config-contents}}"
                - name: command
                  value: "{{inputs.parameters.command}}"