# Default values for capture proxy.
replicaCount: 1
image:
  repository: migrations/capture_proxy
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: LoadBalancer
  port: 9201 # Port exposed to external
  targetPort: 9200 # Container port
container:
  command: >
    /runJavaWithClasspath.sh org.opensearch.migrations.trafficcapture.proxyserver.CaptureProxy
    --kafkaConnection kafka-cluster-kafka-bootstrap:9092
    --destinationUri  https://elasticsearch:19200
    --insecureDestination
    --listenPort 9200
    --sslConfigFile /usr/share/elasticsearch/config/proxy_tls.yml
#--otelCollectorEndpoint http://localhost:4317
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
