apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bulk-loader-unified
  labels:
    {{- include "migration-assistant-chart.labels" . | nindent 4 }}
spec:
  serviceAccountName: argo-workflow-executor
  entrypoint: run-bulk-loaders
  arguments:
    parameters:
      - name: variant-runs
        default: '[{"name":"default"}]'
  templates:
    - name: run-bulk-loaders
      inputs:
        parameters:
          - name: variant-runs
      steps:
        - - name: process-bulk-loads
            template: run-bulk-load
            withParam: "{{ "{{" }}inputs.parameters.variant-runs{{ "}}" }}"
            arguments:
              parameters:
                - name: bulk-load-config
                  value: "{{ "{{" }}item{{ "}}" }}"

    - name: run-bulk-load
      inputs:
        parameters:
          - name: bulk-load-config
      steps:
        - - name: validate-and-extract
            template: validate-and-extract
            arguments:
              parameters:
                - name: bulk-load-config
                  value: "{{ "{{" }}inputs.parameters.bulk-load-config{{ "}}" }}"

        - - name: print-validation-result
            template: print-output
            arguments:
              parameters:
                - name: runtime-options
                  value: "{{ "{{" }}steps.validate-and-extract.outputs.result{{ "}}" }}"
                - name: bulkconfig
                  value: "{{ "{{" }}=inputs.parameters['bulk-load-config']{{ "}}" }}"
                - name: unique-name
                  value: "{{ "{{" }}=jsonpath(inputs.parameters['bulk-load-config'], '$.name'){{ "}}" }}"

        - - name: create-replicaset
            template: create-rs
            arguments:
              parameters:
                - name: runtime-options
                  value: "{{ "{{" }}steps.validate-and-extract.outputs.result{{ "}}" }}"
                - name: unique-name
                  value: "{{ "{{" }}=jsonpath(inputs.parameters['bulk-load-config'], '$.name'){{ "}}" }}"

        - - name: wait-for-completion
            template: check-completion
            arguments:
              parameters:
                - name: runtime-options
                  value: "{{ "{{" }}steps.validate-and-extract.outputs.result{{ "}}" }}"
                - name: unique-name
                  value: "{{ "{{" }}=jsonpath(inputs.parameters['bulk-load-config'], '$.name'){{ "}}" }}"

        - - name: cleanup-replicaset
            template: delete-rs
            arguments:
              parameters:
                - name: unique-name
                  value: "{{ "{{" }}=inputs.parameters['bulk-load-config'].name{{ "}}" }}"

    # New template to print output
    - name: print-output
      inputs:
        parameters:
          - name: runtime-options
          - name: bulkconfig
          - name: unique-name
      script:
        image: migrations/k8s_config_map_util_scripts
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          set -x
          echo everything
          echo {{ "{{" }}=toJson(inputs.parameters['runtime-options']){{ "}}" }}
          echo jsonpath
          echo {{ "{{" }}=jsonpath(inputs.parameters['runtime-options'], '$.documents-per-bulk-request'){{ "}}" }}
          echo nextthing
          echo {{ "{{" }}=inputs.parameters['unique-name']{{ "}}" }}
          echo last thing

    - name: validate-and-extract
      inputs:
        parameters:
          - name: bulk-load-config
      script:
        image: migrations/k8s_config_map_util_scripts
        imagePullPolicy: IfNotPresent
        command: [sh]
        source: |
          set -x

          CONFIG="{{ "{{" }}=toJson(inputs.parameters['bulk-load-config']){{ "}}" }}"
          UNIQUE_NAME=$(echo "$CONFIG" | jq -r '.["name"] // ""')
          TARGET_HOST=$(echo "$CONFIG" | jq -r '.["target-host"] // ""')
          SNAPSHOT_NAME=$(echo "$CONFIG" | jq -r '.["snapshot-name"] // ""')
          echo "Retrieved name: $UNIQUE_NAME" >&2
          echo "Retrieved target-host: $TARGET_HOST" >&2
          echo "Retrieved snapshot-name: $SNAPSHOT_NAME" >&2

          if [ -z "$UNIQUE_NAME" ]; then
            echo "ERROR: 'name' is required but not specified for variant $(echo $CONFIG)"
            exit 1
          fi
          if [ -z "$TARGET_HOST" ]; then
            echo "ERROR: 'target-host' is required but not specified for variant $(echo $CONFIG | jq -r '.name')"
            exit 1
          fi
          if [ -z "$SNAPSHOT_NAME" ]; then
            echo "ERROR: 'snapshot-name' is required but not specified for variant $(echo $CONFIG | jq -r '.name')"
            exit 1
          fi

          echo "Target host and name validation passed for: $TARGET_HOST" >&2

          # Create a JSON object with built-in defaults
          cat > /tmp/defaults.json << EOF
          {
          "replicas": 1,
          "image": "migrations/reindex_from_snapshot:latest",
          "documents-per-bulk-request": "",
          "lease-duration": "",
          "lucene-dir": "/tmp",
          "snapshot-local-dir": "/snapshot",
          "snapshot-name": "",
          "target-insecure": "",
          "target-username": "",
          "target-password": "",
          "status-endpoint": "/status",
          "completion-pattern": "\"status\":\"complete\"",
          "poll-interval-seconds": 30,
          "timeout-minutes": 120
          }
          EOF

          # Extract config excluding name field
          echo $CONFIG | jq 'del(.name)' > /tmp/config-no-name.json

          # Merge with defaults (config values override defaults)
          jq -s '.[0] * .[1]' /tmp/defaults.json /tmp/config-no-name.json


    - name: create-rs
      inputs:
        parameters:
          - name: runtime-options
          - name: unique-name
      resource:
        action: create
        manifest: |
          {{ include "generateRfsDeployment" . | nindent 10 }}


    # Check completion template
    - name: check-completion
      inputs:
        parameters:
          - name: runtime-options
          - name: unique-name
      script:
        image: curlimages/curl:latest
        command: [bash]
        source: |
          set -e

          # Parse runtime options from JSON
          RUNTIME_OPTIONS='{{ "{{" }}inputs.parameters.runtime-options{{ "}}" }}'
          UNIQUE_NAME='{{ "{{" }}inputs.parameters.unique-name{{ "}}" }}'

          # Extract required parameters
          TARGET_HOST=$(echo $RUNTIME_OPTIONS | jq -r '.["target-host"]')
          STATUS_ENDPOINT=$(echo $RUNTIME_OPTIONS | jq -r '.["status-endpoint"]')
          COMPLETION_PATTERN=$(echo $RUNTIME_OPTIONS | jq -r '.["completion-pattern"]')
          POLL_INTERVAL=$(echo $RUNTIME_OPTIONS | jq -r '.["poll-interval-seconds"]')
          TIMEOUT_MINUTES=$(echo $RUNTIME_OPTIONS | jq -r '.["timeout-minutes"]')

          TIMEOUT_SECONDS=$((TIMEOUT_MINUTES * 60))
          ELAPSED_TIME=0

          echo "Starting completion check for bulk-loader-$UNIQUE_NAME"
          echo "Polling $TARGET_HOST$STATUS_ENDPOINT every $POLL_INTERVAL seconds"
          echo "Looking for pattern: $COMPLETION_PATTERN"

          while [ $ELAPSED_TIME -lt $TIMEOUT_SECONDS ]; do
            echo "Checking completion status (${ELAPSED_TIME}s elapsed)..."

            # Make the curl request
            RESPONSE=$(curl -s "${TARGET_HOST}${STATUS_ENDPOINT}")

            # Check if the response contains the completion pattern
            if echo "$RESPONSE" | grep -q "$COMPLETION_PATTERN"; then
              echo "Task completed successfully!"
              exit 0
            fi

            echo "Task still in progress, waiting $POLL_INTERVAL seconds before next check..."
            sleep $POLL_INTERVAL
            ELAPSED_TIME=$((ELAPSED_TIME + POLL_INTERVAL))
          done

          echo "Timeout reached after $TIMEOUT_MINUTES minutes. Task did not complete."
          exit 1

    # Delete ReplicaSet template
    - name: delete-rs
      inputs:
        parameters:
          - name: unique-name
      resource:
        action: delete
        flags: ["--ignore-not-found"]
        manifest: |
          apiVersion: apps/v1
          kind: ReplicaSet
          metadata:
            name: "bulk-loader-{{ "{{" }}inputs.parameters.unique-name{{ "}}" }}"