apiVersion: apps/v1 
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-source
  template:
    metadata:
      labels:
        app: elasticsearch-source
        env: v1
    spec:
      containers:
      - name: elasticsearch
        image: migrations/elasticsearch_searchguard:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch-source
    env: v1
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
