apiVersion: v2
name: migration-assistant
version: 0.1.0
type: application
appVersion: "1.16.0"
dependencies:
  - name: migration-console
    version: "0.1.0"
    repository: "file://../components/migrationConsole"
  - name: bulkload
    version: "0.1.0"
    repository: "file://../components/bulkLoad"
  - name: replayer
    version: "0.1.0"
    repository: "file://../components/replayer"
  - name: capture-proxy
    condition: install-locally-managed-capture-proxy
    version: "0.1.0"
    repository: "file://../components/captureProxy"


#  - name: captured-traffic-kafka-cluster
#    condition: install-locally-managed-kafka
#    version: "0.1.0"
#    repository: "file://../captured-traffic-kafka-cluster"
  - name: grafana
    condition: install-locally-managed-grafana
    version: "8.5.0"
    repository: "https://grafana.github.io/helm-charts"
  - name: prometheus
    condition: install-locally-managed-prometheus
    version: "25.27.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: jaeger
    condition: install-locally-managed-jaeger
    version: "3.2.0"
    repository: "https://jaegertracing.github.io/helm-charts"
#  - name: otel-collector
#    version: 1.2.2
#    repository:
