conditionalPackageInstalls:
  bulkLoader: true
  kafka: true
  replayer: true
  jaeger: false
  prometheus: false
  proxy: false
  grafana: false


capture-proxy:
  enabled: true
  parameters:
    destinationUri:
      configMapName: "source-cluster-endpoint"
      yamlPath: "endpoint"
    insecureDestination:
      configMapName: "source-cluster-endpoint"
      yamlPath: "allow_insecure"

migration-console:
  parameters:
    nothingImportant:
      value: false

bulk-document-loader:
  parameters:
    luceneDir:
      value: /tmp
      allowRuntimeOverride: true
    snapshotName:
      value: rfs
      allowRuntimeOverride: true
    targetHost:
      value: https://opensearch-cluster-master.mcc:9200/
      allowRuntimeOverride: true
    snapshotLocalDir:
      value: /snapshot
      allowRuntimeOverride: true

replayer:
  parameters:
    targetUri:
      value: https://opensearch-cluster-master.mcc:9200/
      allowRuntimeOverride: true


captured-traffic-kafka-cluster:
  environment: test

  kafka-cluster:
    replicas: 1
    storageType: ephemeral
    storageSize: 100Gi
    storageDeleteClaim: true
    dedicatedController:
      replicas: 4
      storageSize: 10Gi

  topicName: "logging-traffic-topic"
  numReplicas: 1
  numPartitions: 1
