conditionalPackageInstalls:
  sharedConfigs: true
  snapshotVolume: true
  logsVolume: false
  migrationConsole: true

  bulkLoader: false
  proxy: true
  kafka: false
  replayer: false
  argoWorkflows: true
  gatekeeper: false
  grafana: false
  prometheus: false
  jaeger: false

  etcd: true

etcd:
  replicaCount: 1
  auth:
    rbac:
      rootPassword: password
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi
  persistence:
    enabled: false
#    storageClass: "standard"
#    size: 10Gi
  service:
    type: ClusterIP
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  extraEnvVars:
    - name: ETCD_AUTO_COMPACTION_RETENTION
      value: "1"
    - name: ETCD_QUOTA_BACKEND_BYTES
      value: "8589934592" # 8GB
    - name: ETCD_HEARTBEAT_INTERVAL
      value: "100"
    - name: ETCD_ELECTION_TIMEOUT
      value: "1000"
  startFromSnapshot:
    enabled: false
  serviceAccount:
    create: true

  podSecurityContext:
    fsGroup: 1001
    runAsUser: 1001

shared-configs:
  globalParameters:
    sourceCluster:
      allowRuntimeOverride: true
      object:
        endpoint: "http://ma-capture-proxy:9200"
        directEndpoint: "http://elasticsearch-master:9200"
        allowInsecure: true
        authType: "no_auth"
        version: "ES_7.10"
    targetCluster:
      allowRuntimeOverride: true
      object:
        endpoint: "https://opensearch-cluster-master:9200"
        allowInsecure: true
        authType: "basic_auth"
        basicAuthUsername: "admin"
        basicAuthPassword: "myStrongPassword123!"
        # Should be in sync with above username/password
        basicAuthHeader: "Basic YWRtaW46bXlTdHJvbmdQYXNzd29yZDEyMyE="
        version: "OS_2.16"
    kafkaBrokers:
      allowRuntimeOverride: false
      object:
        brokers: "captured-traffic-kafka-bootstrap.ma.svc:9092"
        kafkaType: "standard"
    snapshot:
      allowRuntimeOverride: true
      object:
        #otelEndpoint: "http://localhost:4317"
        repoPath: "/snapshot"
        snapshotName: "migration-assistant-snapshot"
        snapshotType: "fs"
    metadataMigration:
      allowRuntimeOverride: true
      object:
        minReplicas: 0
        metadataType: "from_snapshot"
        #otelEndpoint: "http://localhost:4317"
        sourceClusterVersion: "ES_7.10"
#    metricsSource:
#      allowRuntimeOverride: false
#      object:
#        endpoint: "http://prometheus:9090"
#        observabilityType: "prometheus"


capture-proxy:
  parameters:
    destinationUri:
      source: otherConfig
      configMapName: "source-cluster"
      configMapKey: "directEndpoint"
    insecureDestination:
      source: otherConfig
      configMapName: "source-cluster"
      configMapKey: "allowInsecure"
    kafkaConnection:
      source: otherConfig
      configMapName: "kafka-brokers"
      configMapKey: "brokers"


migration-console:
  snapshotVolumeEnabled: true
  snapshotVolumePvc: "snapshot-volume-pvc"
  sharedLogsVolumeEnabled: true
  sharedLogsPvc: "shared-logs-pvc"


bulk-document-loader:
  snapshotVolumeEnabled: true
  snapshotVolumePvc: "snapshot-volume-pvc"
  sharedLogsVolumeEnabled: true
  sharedLogsPvc: "shared-logs-pvc"
  parameters:
    snapshotName:
      source: otherConfig
      configMapName: "snapshot"
      configMapKey: "snapshotName"
    targetHost:
      source: otherConfig
      configMapName: "target-cluster"
      configMapKey: "endpoint"
    targetInsecure:
      source: otherConfig
      configMapName: "target-cluster"
      configMapKey: "allowInsecure"
      parameterType: booleanFlag
    targetUsername:
      source: otherConfig
      configMapName: "target-cluster"
      configMapKey: "basicAuthUsername"
    targetPassword:
      source: otherConfig
      configMapName: "target-cluster"
      configMapKey: "basicAuthPassword"
    sourceVersion:
      source: parameterConfig
      value: "ES_7.10"
      allowRuntimeOverride: true
    docTransformerConfigFile:
      source: parameterConfig
      value: "/shared-logs-output/test-transformations/transformation.json"
      allowRuntimeOverride: true


replayer:
  sharedLogsVolumeEnabled: true
  sharedLogsPvc: "shared-logs-pvc"
  parameters:
    kafkaTrafficBrokers:
      source: otherConfig  # eventually this will become a list from a shared config
      configMapName: "kafka-brokers"
      configMapKey: "brokers"
    targetUri:
      source: otherConfig
      configMapName: "target-cluster"
      configMapKey: "endpoint"
    insecure:
      source: otherConfig
      configMapName: "target-cluster"
      configMapKey: "allowInsecure"
      parameterType: booleanFlag
    authHeaderValue:
      source: otherConfig
      configMapName: "target-cluster"
      configMapKey: "basicAuthHeader"
    speedupFactor:
      source: parameterConfig
      value: 10
      allowRuntimeOverride: true
    transformerConfigFile:
      source: parameterConfig
      value: "/shared-logs-output/test-transformations/transformation.json"
      allowRuntimeOverride: true


captured-traffic-kafka-cluster:
  environment: test

  clusterName: captured-traffic

  replicas: 1
  storageType: ephemeral
  storageSize: 100Gi
  storageDeleteClaim: true
  dedicatedController:
    replicas: 1
    storageSize: 10Gi


argo-workflows:
  fullnameOverride: "argo"
  controller:
    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    clusterWorkflowTemplates:
      enabled: false
    metricsConfig: # to publish
      enabled: true
  server:
    extraArgs:
      - --auth-mode=server
  serviceAccount:
    create: true
  singleNamespace: true
  # Extra workflow configuration
  workflow:
    serviceAccount:
      create: false
      name: argo-workflow-executor


workflowService:
  defaultEnvVars:
    ENV_VAR1: "default-value-1"
    ENV_VAR2: "default-value-2"
  defaultReplicas: 1
  monitorImage: "bitnami/kubectl:latest"
  allowedRepos:
    - "bitnami/"
#    - "k8s.gcr.io/"
#    - "docker.io/library/"


gatekeeper:
  auditInterval: 60
  constraintViolationsLimit: 20
  enableExternalData: true
  audit:
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  controllerManager:
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi


jaeger:
  allInOne:
    enabled: true
  provisionDataStore:
    cassandra: false
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

grafana:
  ## Grafana data sources configuration
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.prometheus.svc.cluster.local:9090
          isDefault: true
          editable: true
        - name: Jaeger
          type: jaeger
          access: proxy
          url: http://jaeger-query.jaeger.svc.cluster.local:16686
          isDefault: false
          editable: true

  ## Set up the sidecar to import data sources (usually enabled by default)
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true
      label: grafana_dashboard
