conditionalPackageInstalls:
  kafka: true
  jaeger: true
  prometheus: true
  grafana: true

proxy:
  enabled: true
  parameters:
    destinationUri:
      configMapName: "sourceClusterEndpoint" # this value will be used to pull the destination uri
      yamlPath: "endpoint"
    insecureDestination:
      configMapName: "sourceClusterEndpoint" # this value will be used to pull the destination uri
      yamlPath: "allow_insecure"
