volume:
  volumeName: snapshot-vol
  mountPath: /storage # Path inside the container where the volume should be mounted
  # Persistent volume claim settings
  pvcClaimName: snapshot-vol-pvc
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi
