receivers:
  otlp:
    protocols:
      grpc:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:
  filelog:
    include: [ /logs/metrics.log ]

processors:
  memory_limiter:
    limit_mib: 300
  batch:
  # filter:
  #   attributes:
  #     include:
  #       - "service.name"
  #       - "span.kind"

extensions:
  basicauth/client:
    client_auth: 
      username: "admin"
      password: "admin"
  pprof:
    endpoint: "localhost:1777"

exporters:
  opensearch:
    http:
      endpoint: "https://opensearchanalytics:9200"
      auth:
        authenticator: basicauth/client
      tls:
        insecure_skip_verify: true
    # index: "logs"
  logging:

service:
  extensions: [pprof, basicauth/client]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [opensearch]
    metrics:
      receivers: [hostmetrics]
      processors: []
      exporters: [logging]
    logs/2:
      receivers: [filelog]
      processors: []
      exporters: [logging]