title: Opensearch Migrations
description: Documentation for Opensearch Migrations
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Use the existing Markdown files
include:
  - "*.md"

# Define custom collections for organizing content
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Define the default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: default