# templates/create-s3-bucket-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: create-argo-migration-workflows-{{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: create-argo-migration-workflows
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration-console-for-workflows
          image: amazon/aws-cli:2.25.11
          command:
            - /bin/sh
            - -c
            - |
              set -x
