apiVersion: v2
name: observability
version: 0.1.0
dependencies:
  - name: migration-assistant
    version: "0.1.0"
    repository: "file://../migrationAssistant"
  - name: mock-customer-resources
    version: "0.1.0"
    repository: "file://../mockCustomerClusters"
