apiVersion: v2
name: observability
version: 0.1.0
dependencies:
  - name: migration-assistant
    version: "0.1.0"
    repository: ""
  - name: test
    version: "25.27.0"
    repository: "https://prometheus-community.github.io/helm-charts"
