apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-image-config
  labels:
    # Necessary label for Argo to pull values from a configmap
    workflows.argoproj.io/configmap-type: Parameter

data:
  captureProxyImage: "{{ .Values.images.captureProxy.repository }}:{{ .Values.images.captureProxy.tag }}"
  trafficReplayerImage: "{{ .Values.images.trafficReplayer.repository }}:{{ .Values.images.trafficReplayer.tag }}"
  reindexFromSnapshotImage: "{{ .Values.images.reindexFromSnapshot.repository }}:{{ .Values.images.reindexFromSnapshot.tag }}"
  migrationConsoleImage: "{{ .Values.images.migrationConsole.repository }}:{{ .Values.images.migrationConsole.tag }}"
