source_cluster: ???
target_cluster: ???
backfill:
  reindex_from_snapshot:
    snapshot_name: ???
    snapshot_repo: ???
clientOptions:
  user_agent_extra: ???
kafka:
  broker_endpoints: ???
  ??? if mode  ???
metrics_source:
  ??? implementation ???
replay:
  docker:
snapshot:
  snapshot_name: "rfs-snapshot"
  fs:
    repo_path: "/storage/snapshot"
  otel_endpoint: "http://localhost:4317"
metadata_migration:
  from_snapshot:
  min_replicas: 0
  otel_endpoint: "http://localhost:4317"
