name: Codecov Publish

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  publish-codecov:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-reports-*
          path: ./coverage-reports

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage-reports/**/*.*
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
