name: Codecov Publish

# Due to the behavior of workflow_run, changes to this file will
# only be reflected once they are pushed up to the `default` (main) branch

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  publish-codecov:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-reports-*
          path: ./coverage-reports
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Upload coverage report
        if: '!cancelled()'
        uses: codecov/codecov-action@v4
        with:
          override_commit: ${{ github.event.workflow_run.head_sha }}
          override_pr: ${{ github.event.workflow_run.pull_requests[0].number }}
          override_branch: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /**/coverage-reports/**/*.*
          flags: unittests
          fail_ci_if_error: true
          verbose: true